# Generated by Django 5.2.8 on 2025-11-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "Id of studnet",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
                ("Name of Studnet", models.CharField(max_length=100)),
                ("Batch of Studnet", models.CharField()),
                ("Roll no of student", models.CharField(max_length=25, unique=True)),
                ("City of Student", models.CharField(max_length=100)),
            ],
        ),
    ]
