# Generated by Django 5.2.8 on 2025-11-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="Id of studnet",
            field=models.UUIDField(
                auto_created=True, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
