# Generated by Django 5.2.8 on 2025-11-06 08:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_alter_students_id_of_studnet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="Id of studnet",
            field=models.UUIDField(
                auto_created=uuid.UUID("b94fdfbe-5df3-405f-b8b7-5cf2af0fe12e"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
