# Generated by Django 5.2.8 on 2025-11-06 08:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_alter_students_id_of_studnet"),
    ]

    operations = [
        migrations.RenameField(
            model_name="students",
            old_name="City of Student",
            new_name="city",
        ),
        migrations.RenameField(
            model_name="students",
            old_name="Name of Studnet",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="students",
            old_name="Roll no of student",
            new_name="roll_number",
        ),
        migrations.RemoveField(
            model_name="students",
            name="Batch of Studnet",
        ),
        migrations.RemoveField(
            model_name="students",
            name="Id of studnet",
        ),
        migrations.AddField(
            model_name="students",
            name="batch",
            field=models.CharField(default=2025, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="students",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
