# Generated by Django 5.2.8 on 2025-11-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_rename_city_of_student_students_city_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="students",
            options={"verbose_name": "Student", "verbose_name_plural": "Students"},
        ),
        migrations.AlterField(
            model_name="students",
            name="batch",
            field=models.PositiveIntegerField(),
        ),
    ]
